Fix settings page
GospelAid/badiup pull request #153
Opened 2020-03-05 10:11 UTC by charleshenryhugo

PR #139 introduced some issues such as :
1. When a customer enters in the settings page and then clicks `保存` button, the admin-order-list page is returned.
2. The database shouldn't be updated when the admin switches the `taxInclusiveBoolValue` between `true` and `false`. The database should be updated when `保存` is clicked.
Operating database update when the admin clicks the switch button makes the button move slowly.

Some changes were made in this PR to fix the issues above.

2020-03-05 10:28 UTC, dragonfly91 requested changes
Left some refactoring comments.

2020-03-05 10:28 UTC, dragonfly91 commented on lib/screens/settings_page.dart
> +    if (currentSignedInUser.isAdmin()) {
Can we do this update in the `AdminSettingsListing` widget?

2020-03-05 10:28 UTC, dragonfly91 commented on lib/widgets/admin_settings_listing.dart
> +bool taxInclusiveBoolValue;
Based on the previous comment, this could be a private variable

2020-03-05 10:31 UTC, dragonfly91 commented
Also, can you post a video about how the switch button responds with your changes? @charleshenryhugo

2020-03-05 11:13 UTC, charleshenryhugo commented on lib/screens/settings_page.dart
> +    if (currentSignedInUser.isAdmin()) {
I am stuck at how to call the functions of `AdminSettingsListing` widget from `SettingsPage` widget.

2020-03-05 13:47 UTC, dragonfly91 commented on lib/screens/settings_page.dart
> +    if (currentSignedInUser.isAdmin()) {
In `settings_page.dart`:

```
Future<void> _saveCurrentSignedInUserData() async {
    await db
        .collection(constants.DBCollections.users)
        .document(currentSignedInUser.email)
        .updateData(currentSignedInUser.toMap());
}
```

In `admin_settings_listing.dart`:

```
...
          Switch(
            activeColor: Colors.white,
            activeTrackColor: paletteForegroundColor,
            value: currentSignedInUser.setting.taxInclusive,
            onChanged: (bool value) {
              setState(() {
                currentSignedInUser.setting.taxInclusive = value;
              });
            },
          )
...
```

2020-03-05 14:01 UTC, dragonfly91 commented
https://github.com/GospelAid/badiup/issues/150 need not be fixed if this PR goes thru.

2020-03-06 05:53 UTC, charleshenryhugo commented on lib/screens/settings_page.dart
> +    if (currentSignedInUser.isAdmin()) {
Wanted to write as you suggested!
However, if the user clicks the switch button and then just goes back to the previous page without clicking the `保存` button, 
only the `currentSignedInUser.setting.taxInclusive` will be updated, while the database keeps the old record.

2020-03-07 14:36 UTC, dragonfly91 approved these changes

2020-03-07 14:36 UTC, merged