Add about badi banner and about badi page
GospelAid/badiup pull request #156
Opened 2020-03-07 08:59 UTC by charleshenryhugo

fixes #141 

video link:
https://youtu.be/ZRPO4-0cb70

2020-03-07 14:57 UTC, dragonfly91 commented
I think the idea is to count the number of times the app has been opened and not the number of times the user has signed in. Can you check this for a solution? https://stackoverflow.com/questions/59162178/how-to-check-if-user-open-my-app-first-time-flutter-app-dart-code

2020-03-09 10:07 UTC, dragonfly91 requested changes

2020-03-09 10:07 UTC, dragonfly91 commented on lib/models/admin_model.dart
> +          email: email,
Was this because of the auto format ?

2020-03-09 10:07 UTC, dragonfly91 commented on lib/screens/about_badi_page.dart
> +final String _castSystemIntroText = """
I thought a while about this, but I think we need to make this text editable for Admin. This should be part of the settings page which the admin can view and edit. Because this text cannot be hard coded. I think we need a redesign from Miho. For now, maybe you can offload the text to firestore and read it from there. Let me know your thoughts on this.v

2020-03-09 10:07 UTC, dragonfly91 commented on lib/widgets/product_listing.dart
> +            bool _firstTimeOpenApp = snapshot.data
consider renaming this to `appOpenedFirstTime`

2020-03-09 13:34 UTC, charleshenryhugo commented on lib/models/admin_model.dart
> +          email: email,
Yes. When I run `flutter format lib/models/admin_model.dart`, it becomes like this.
Not so beautiful to me.

2020-03-09 13:43 UTC, charleshenryhugo commented on lib/screens/about_badi_page.dart
> +final String _castSystemIntroText = """
I will store the text into firestore.
Should it be stored in the database or the storage?

2020-03-12 00:21 UTC, ghost approved these changes
I confirmed , it's ok

2020-03-12 23:47 UTC, dragonfly91 approved these changes
LGTM. One minor comment. You can merge after addressing it.

2020-03-12 23:47 UTC, dragonfly91 commented on lib/screens/about_badi_page.dart
> +        _buildCastSystemIntro(),
nit: rename to `_buildCasteSystemIntro`

2020-03-13 07:23 UTC, merged