Check for "add to cart"
GospelAid/badiup pull request #211
Opened 2020-04-05 02:43 UTC by DavidCuentasMar

2020-04-07 13:30 UTC, dragonfly91 requested changes

2020-04-07 13:30 UTC, dragonfly91 commented on lib/screens/customer_product_detail_page.dart
> +        '色］［サイズ］を選択してください',
You can use this text:

when stockType = sizeAndColor, "色・サイズ　を選択してください"
when stockType = sizeOnly, "サイズを選択してください"
when stockType = colorOnly, "色を選択してください"

2020-04-09 03:20 UTC, DavidCuentasMar commented on lib/screens/customer_product_detail_page.dart
> +        '色］［サイズ］を選択してください',
How the quantityOnly should behave? I found this case and not sure how to proceed

2020-04-09 09:14 UTC, dragonfly91 commented on lib/screens/customer_product_detail_page.dart
> +        '色］［サイズ］を選択してください',
@DavidCuentasMar we don't need to show any text when stockType = quantityOnly 
These Japanese texts basically are alerting the user "please select size and / or color". This is not needed when only quantity is present. Does this answer your question?

2020-04-09 09:35 UTC, dragonfly91 requested changes

2020-04-09 09:35 UTC, dragonfly91 commented on lib/screens/customer_product_detail_page.dart
> +    if (_selectedItemColor != null && _selectedItemSize != null) {
I think this check is valid only for `stockType` = `sizeAndColor`. 

You can add a helper method like this:
```
bool _canAddToCart() {
  if (_product.stock.stockType == StockType.sizeAndColor) {
    return _selectedItemColor != null && _selectedItemSize != null;
  } else if (_product.stock.stockType == StockType.sizeOnly) {
    return _selectedItemSize != null;
  } else if (_product.stock.stockType == StockType.colorOnly) {
    return _selectedItemColor != null;
  }
  return true;
}
```
Then, you can use this method in the `GestureDetector` widget of `_buildAddToCartButton`:
```
if (_canAddToCart()) {
  _addToCart();
} else {
  setState(() {
    _showAddToCartFailedMessage = true;
  });
}
```
This way, you don't have to modify the `_addToCart` method.

2020-04-09 09:35 UTC, dragonfly91 commented on lib/screens/customer_product_detail_page.dart
> +    String failMessage;
A better name could be `errorMessage`

2020-04-09 09:35 UTC, dragonfly91 commented on lib/screens/customer_product_detail_page.dart
> +          if (_selectedItemColor != null && _selectedItemSize != null) {
Please refer to my comment below. Snack bar should be shown whenever _addToCart succeeds:
```
if (_canAddToCart()) {
  _addToCart();
  _scaffoldKey.currentState.showSnackBar(      // <------- Add here!
    _buildAddedToCartNotification(),
  );
} else {
  setState(() {
    _showAddToCartFailedMessage = true;
  });
}
```

2020-04-09 14:53 UTC, DavidCuentasMar commented
In the last commit I removed one streambuilder (it was in _buildAppBar) and moved the other one to build method, this represents only making 1 api call and having access to product object in all widgets. Tell what you think about this.

2020-04-10 12:07 UTC, dragonfly91 approved these changes

2020-04-10 12:07 UTC, merged